# Generated by Django 3.0.1 on 2019-12-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='adddress',
            new_name='address',
        ),
    ]
